services:
  php-fpm:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - symfony-network

  nginx:
    image: teclaelvis01/nginx:0.0.1
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.devcontainer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - symfony-network

  mysql:
    image: teclaelvis01/mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ch24db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  mysql_data: 