<?php  //[STAMP] 3065290173c5fc6bbe00cd20460df949
// phpcs:ignoreFile
namespace Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
